name: ETL Pipeline
run-name: Daily ETL Pipeline Run
env:
  PYTHON_VERSION: "3.10"
  AUTOMATION_USERNAME: "jonruida"
  AUTOMATION_EMAIL: "ruiz.carrillo.idarreta@gmail.com"

on:
  workflow_dispatch:
  schedule:
    - cron: "21 7 * * *"

jobs:
  run-etl-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
           token: ${{ secrets.GIT_P_10_TOKEN }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ETL Pipeline
        run: |
          python src/pipeline.py

      - name: Peek Data output
        run: |
          head -n 10 data/air_data.csv

      - name: Commit report
        run: |
          git config --global user.name $AUTOMATION_USERNAME
          git config --global user.email $AUTOMATION_EMAIL
          git add data/.
          git commit -m "Updating Data"
          git push

